#!/bin/python3

from signal import signal, SIGPIPE, SIG_DFL
signal(SIGPIPE,SIG_DFL)

import sys

with open(sys.argv[1], "r") as file:
    cont = file.readlines()
    for i, line in enumerate(cont):
        firstSpace = True
        if len(line) != 1:
            newline = ""
            space = 0
            if i > 2:
                for char in line:
                    if char == " ":
                        space += 1
                    else:
                        if space != 0:
                            if firstSpace:
                                firstSpace = False
                            else:
                                newline += "\\hspace{" + str(space*2) + "mm}"
                            space = 0
                        newline += char
                cont[i] = "\\noindent\\hspace*{-9mm}\\texttt{" + newline[:-1] + "}\\\\\n"
            elif i == 2:
                for char in line:
                    if char == " ":
                        space += 1
                    else:
                        if space != 0:
                            newline += "\\hspace{" + str(space-1) + "mm}"
                            space = 0
                        newline += char
                cont[i] = "\\noindent\\texttt{" + newline[:-1] + "}\\\\\n"
            else: 
                for char in line:
                    if char == " ":
                        space += 1
                    else:
                        if space != 0:
                            newline += "\\hspace{" + str(space) + "mm}"
                            space = 0
                        newline += char
                cont[i] = "\\noindent\\texttt{" + newline[:-1] + "}\\\\\n"
            cont[i] = cont[i][:9] + "\\hspace{8mm}" + cont[i][9:]
        
    cont += "\n\\vspace{2mm}\n}}}\n\\end{center}\n"
    cont = "\\begin{center}\\scalebox{.55}{\n\\noindent\\fbox{%\n\\parbox{\\linewidth}{%\n\\centering\n" + ''.join(cont)
    sys.stdout.write(''.join(cont))
